### ISSUE TITLE
License and directory depth

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/pyme-plugin#1]
We should really make this BSD licensed

Also, the python-microscopy directory (and arguably even the module subdirectories) are redundant and confusing. We could move everything up one level. I'm generally against plugins having a python-microscopy directory within plugins

**Comment by barentine** [comment]
The directory structure was a hold over from the thought that someone might have a stand-alone package that then wants to add pyme support, but that makes it unlikely they would start from a template repository ;) Should be sorted now.
