### ISSUE TITLE
Is setup.py supposed to be up a level?

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/pyme-plugin#11]
From the way it calls `install_plugin.py`, I think it's supposed to be up a level.

**Comment by barentine** [comment]
yeah I probably didn't get that right when I added it in #3, mostly copying what I had in a plugin which came before #2

Alternative would be to remove the extra `PACKAGE_NAME` in the path which would make it even easier to use right?

mind PRing if you're testing it @zacsimile ?

**Comment by zacsimile** [comment]
It seems to work up a level and I personally think it makes more sense to include `setup.py` in the root and `install_plugin.py` within the plugin directory (PYME, for example, has `setup.py` in the `python-microscopy` top level directory). I'll PR.
